# COMMON
DOMAIN_URL="http://localhost"
REGISTRY_KEY=""
CACHE_DIR=""
CACHE_ROOT_URL=""

# BOT
BOT_TOKEN=""
URL_PREFIX="/"
INLINE_CACHE_TIME=180

# MEILISEARCH
MEILISEARCH_URL="http://localhost:7700"
MEILISEARCH_MASTERKEY=""
