version: '3.7'

services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.28
    ports:
      - 7700:7700
    volumes:
      - ./data/meili_data:/meili_data
    command: 'meilisearch --env="development"'
    environment:
      - MEILI_MASTER_KEY=meilisearch-master-key
  bot:
    container_name: inline-bot
    build: .
    volumes:
      - .:/app
    ports:
      - 8001:8001
    environment:
      - BOT_CONFIG=/app/env.py
    command: "sanic inlinebot:app -H 0.0.0.0 -p 8001 -w 1"
  nginx:
    container_name: inline-nginx
    image: nginx:alpine
    