version: '3.7'

services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.28
    ports:
      - 7700:7700
    volumes:
      - ./data/meili_data:/meili_data
    environment:
      - MEILI_MASTER_KEY=meilisearch-master-key
    command: 'meilisearch --env="development"'